name: GitHub Pages

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0
      
      - name: Fetch Notion pages
        run: python script.py --static static/images --content content/posts --url /mohamedhuzien.github.io/images --db ${{ secrets.NOTION_DB_ID }} --key ${{ secrets.NOTION_API_KEY }} --hugo

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      - name: Build
        run: hugo
      - name: Deploy
        uses: actions/deploy-pages@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          path: ./public
          branch: gh-pages
